version: '2'
services:
  app:
    extends:
      file: docker/docker-compose.common.yml
      service: app
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app/

  shell-checker:
    image: koalaman/shellcheck-alpine:v0.7.1
    working_dir: /mnt/
    command:
      - scripts/lint_app.sh
    volumes:
      - .:/mnt/
    deploy:
      replicas: 0 # run as one-off process not part of doker-compose up

